spring:
  application:
    name: concert-hub-backend

  profiles:
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/concerthub?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: concerthub
    password: concerthub

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

jwt:
  secret: concerthub-jwt-secret-key-for-development-environment-only
  access-token-expiration: 1800000    # 30분 (밀리초)
  refresh-token-expiration: 604800000  # 7일 (밀리초)